### Numpy
#### Задача №1

In [24]:
import numpy as np

list_1 = [0,1,2,3,4]
arr_1d = np.array(list_1)
print(arr_1d)

[0 1 2 3 4]


In [25]:
arr = np.linspace(1, 100, 100)
arr = arr[arr%5 == 0]
print(arr)

[  5.  10.  15.  20.  25.  30.  35.  40.  45.  50.  55.  60.  65.  70.
  75.  80.  85.  90.  95. 100.]


#### Задача №2

In [26]:
arr_10 = arr[arr%10 == 0]
print(arr_10)

[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


#### Задача №3

In [27]:
my_arr = arr_10.reshape(5,2)
print(my_arr)

[[ 10.  20.]
 [ 30.  40.]
 [ 50.  60.]
 [ 70.  80.]
 [ 90. 100.]]


#### Задача №4

In [28]:
my_second_arr = my_arr - np.full((5,2), 5)
print(my_second_arr)

[[ 5. 15.]
 [25. 35.]
 [45. 55.]
 [65. 75.]
 [85. 95.]]


#### Задача №5

In [29]:
result = np.concatenate((my_arr, my_second_arr),axis=1)
print(result)

[[ 10.  20.   5.  15.]
 [ 30.  40.  25.  35.]
 [ 50.  60.  45.  55.]
 [ 70.  80.  65.  75.]
 [ 90. 100.  85.  95.]]


#### Задача №6

In [30]:
new_result = np.copy(result)
new_result[1:3] = result[1:3]/my_arr[0:4].T
print (new_result)

[[ 10.          20.           5.          15.        ]
 [  3.           1.33333333   0.5          0.5       ]
 [  2.5          1.5          0.75         0.6875    ]
 [ 70.          80.          65.          75.        ]
 [ 90.         100.          85.          95.        ]]


#### Задача №7

In [31]:
n_result = result[np.where(new_result == result)]
print (n_result)

[ 10.  20.   5.  15.  70.  80.  65.  75.  90. 100.  85.  95.]


#### Задача №8

In [32]:
arr_3 = n_result.reshape(3,4)
tmp = np.copy(arr_3)
arr_3[2], arr_3[0] = tmp[0], tmp[2] 

print(arr_3)

[[ 90. 100.  85.  95.]
 [ 70.  80.  65.  75.]
 [ 10.  20.   5.  15.]]


#### Задача №9

In [33]:
print(np.mean(arr_3, axis=1))
print(np.median(arr_3, axis=1))
print(np.std(arr_3, axis=1))

[92.5 72.5 12.5]
[92.5 72.5 12.5]
[5.59016994 5.59016994 5.59016994]


#### Задача №10

In [34]:
x = np.copy(arr_3)
arr_normed = x / x.max(axis=1)[:,np.newaxis]
arr_normed

array([[0.9   , 1.    , 0.85  , 0.95  ],
       [0.875 , 1.    , 0.8125, 0.9375],
       [0.5   , 1.    , 0.25  , 0.75  ]])

#### Задача с пи

In [35]:
n = 10000
array = np.random.rand(n, 2)

In [36]:
r = np.sum(array*array, axis=1)
np.sqrt(r)
nin = np.where(r<=1)[0].shape[0]
pi = 4*nin/n
print(pi)

3.1152


### Pandas 


In [37]:
import pandas as pd

data = pd.read_csv('adult.txt', sep=', ')
data.head(370)

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  This is separate from the ipykernel package so we can avoid doing imports until


age         workclass  fnlwgt     education  education-num  \
0     39         State-gov   77516     Bachelors             13   
1     50  Self-emp-not-inc   83311     Bachelors             13   
2     38           Private  215646       HS-grad              9   
3     53           Private  234721          11th              7   
4     28           Private  338409     Bachelors             13   
5     37           Private  284582       Masters             14   
6     49           Private  160187           9th              5   
7     52  Self-emp-not-inc  209642       HS-grad              9   
8     31           Private   45781       Masters             14   
9     42           Private  159449     Bachelors             13   
10    37           Private  280464  Some-college             10   
11    30         State-gov  141297     Bachelors             13   
12    23           Private  122272     Bachelors             13   
13    32           Private  205019    Assoc-acdm             12   
14    40           Private  121772     Assoc-voc             11   
15    34           Private  245487       7th-8th              4   
16    25  Self-emp-not-inc  176756       HS-grad              9   
17    32           Private  186824       HS-grad              9   
18    38           Private   28887          11th              7   
19    43  Self-emp-not-inc  292175       Masters             14   
20    40           Private  193524     Doctorate             16   
21    54           Private  302146       HS-grad              9   
22    35       Federal-gov   76845           9th              5   
23    43           Private  117037          11th              7   
24    59           Private  109015       HS-grad              9   
25    56         Local-gov  216851     Bachelors             13   
26    19           Private  168294       HS-grad              9   
27    54                 ?  180211  Some-college             10   
28    39           Private  367260       HS-grad              9   
29    49           Private  193366       HS-grad              9   
..   ...               ...     ...           ...            ...   
340   26           Private   94936    Assoc-acdm             12   
341   38           Private  296478     Assoc-voc             11   
342   36         State-gov  119272       HS-grad              9   
343   33           Private   85043       HS-grad              9   
344   22         State-gov  293364  Some-college             10   
345   43  Self-emp-not-inc  241895     Bachelors             13   
346   67                 ?   36135          11th              7   
347   30                 ?  151989     Assoc-voc             11   
348   56           Private  101128    Assoc-acdm             12   
349   31           Private  156464     Bachelors             13   
350   33           Private  117963     Bachelors             13   
351   26           Private  192262       HS-grad              9   
352   33           Private  111363     Bachelors             13   
353   46         Local-gov  329752          11th              7   
354   59                 ?  372020     Bachelors             13   
355   38       Federal-gov   95432       HS-grad              9   
356   65           Private  161400          11th              7   
357   40           Private   96129     Assoc-voc             11   
358   42           Private  111949       HS-grad              9   
359   26  Self-emp-not-inc  117125           9th              5   
360   36           Private  348022          10th              6   
361   62           Private  270092       Masters             14   
362   43           Private  180609     Bachelors             13   
363   43           Private  174575     Bachelors             13   
364   22           Private  410439       HS-grad              9   
365   28           Private   92262       HS-grad              9   
366   56  Self-emp-not-inc  183081  Some-college             10   
367   22           Private  362589    Assoc-acdm    

#### Задача №1. Сколько в датасете мужчин, сколько женщин? (sex, male, female) ТЗ: =2 строки

In [38]:
data['sex'].value_counts()

Male      21790
Female    10771
Name: sex, dtype: int64

#### Задача №2. Какой средний возраст у мужчин, какой у женщин? ТЗ: =2 строки

In [39]:
data.groupby(['sex'])['age'].mean()

sex
Female    36.858230
Male      39.433547
Name: age, dtype: float64

#### Задача №3. Какой процент из общей выборки составляют представители Кубы (native-country)? ТЗ: =1 строка

In [40]:
(data[data['native-country'] == 'Cuba'].shape[0] / data['native-country'].count())*100

0.29176008107859097

#### Задача №4-5. Посчитайте среднее значение и стандартное отклонение возраста (age) для двух групп (salary): кто зарабатывает меньше 50K, кто зарабатывает больше 50К в год. ТЗ: =2 строки

In [41]:
print("Средний возраст:", data.groupby(['salary'])['age'].mean())
print("Стандартное отклонение возраста:", data.groupby(['salary'])['age'].std())

Средний возраст: salary
<=50K    36.783738
>50K     44.249841
Name: age, dtype: float64
Стандартное отклонение возраста: salary
<=50K    14.020088
>50K     10.519028
Name: age, dtype: float64


#### Задача №6. Какой процент людей, которые зарабывают больше 50К имеют высшее образование (признак education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate feature)? Воспользуйтесь pd.unique() и .isin(). ТЗ: <=5 строк

In [42]:
df_salary = data[data['salary'] == '>50K']
edu = ['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate']
df = df_salary[df_salary['education'].isin(edu)]
percent = (df.shape[0] / df_salary.shape[0]) * 100
print("Процент:", percent)


Процент: 57.83701058538452


#### Задача №7. Покажите статистики по возрасту (age) для представителей разных рас (race) и гендеров (sex). Используйте groupby() и describe() методы. ТЗ: =1 строка

In [43]:
data.groupby(['age'])['race', 'sex'].describe(percentiles=[])

race                      sex                    
    count unique    top freq count unique     top freq
age                                                   
17    395      5  White  349   395      2    Male  209
18    550      5  White  483   550      2    Male  282
19    712      5  White  630   712      2  Female  356
20    753      5  White  653   753      2    Male  390
21    720      5  White  627   720      2    Male  391
22    765      5  White  648   765      2    Male  423
23    877      5  White  729   877      2    Male  518
24    798      5  White  662   798      2    Male  493
25    841      5  White  707   841      2    Male  528
26    785      5  White  648   785      2    Male  495
27    835      5  White  693   835      2    Male  541
28    867      5  White  715   867      2    Male  557
29    813      5  White  670   813      2    Male  542
30    861      5  White  721   861      2    Male  588
31    888      5  White  747   888      2    Male  606
32    828      5  White  703   828      2    Male  573
33    875      5  White  720   875      2    Male  620
34    886      5  White  752   886      2    Male  629
35    876      5  White  733   876      2    Male  630
36    898      5  White  763   898      2    Male  611
37    858      5  White  738   858      2    Male  629
38    827      5  White  709   827      2    Male  591
39    816      5  White  690   816      2    Male  560
40    794      5  White  685   794      2    Male  531
41    808      5  White  684   808      2    Male  575
42    780      5  White  661   780      2    Male  552
43    770      5  White  650   770      2    Male  541
44    724      5  White  607   724      2    Male  522
45    734      5  White  614   734      2    Male  512
46    737      5  White  632   737      2    Male  509
..    ...    ...    ...  ...   ...    ...     ...  ...
60    312      5  White  273   312      2    Male  233
61    300      4  White  260   300      2    Male  221
62    258      4  White  228   258      2    Male  170
63    230      5  White  204   230      2    Male  166
64    208      3  White  196   208      2    Male  138
65    178      5  White  163   178      2    Male  121
66    150      4  White  126   150      2    Male  102
67    151      4  White  135   151      2    Male   99
68    120      3  White  110   120      2    Male   78
69    108      3  White  101   108      2    Male   75
70     89      3  White   83    89      2    Male   61
71     72      4  White   66    72      2    Male   46
72     67      3  White   60    67      2    Male   42
73     64      2  White   60    64      2    Male   42
74     51      4  White   43    51      2    Male   32
75     45      3  White   37    45      2    Male   31
76     46      2  White   44    46      2    Male   30
77     29      3  White   26    29      2    Male   20
78     23      3  White   20    23      2    Male   16
79     22      2  White   21    22      2    Male   17
80     22      2  White   21    22      2    Male   17
81     20      2  White   19    20      2    Male   11
82     12      2  White   11    12      2    Male   10
83      6      1  White    6     6      2    Male    5
84     10      2  White    9    10      2    Male    6
85      3      1  White    3     3      2    Male    2
86      1      1  White    1     1      1  Female    1
87      1      1  White    1     1      1    Male    1
88      3      1  White    3     3      2    Male    2
90     43      3  White   34    43      2    Male   29

[73 rows x 8 columns]

#### Задача №8. Какие мужчины чаще зарабатывают больше 50К: женатые или одинокие (marital-status)? Примите, что женатыми являются все, у кого marital-status начинается с Married. ТЗ: <=4 строк

In [44]:
df_salary = data[(data['salary'] == '>50K') & (data['sex'] == 'Male')]
df_salary['marital-status'].value_counts()

Married-civ-spouse       5938
Never-married             325
Divorced                  284
Separated                  49
Widowed                    39
Married-spouse-absent      23
Married-AF-spouse           4
Name: marital-status, dtype: int64

#### Задача №9. Какое максимальное значение по количеству рабочих часов в неделю (hours-per-week)? Как много людей, которые столько работают и какой процент среди них зарабатывает больше 50К? ТЗ: <=4 строк

In [45]:
print("Максимальное количество рабочих часов в неделю: ", data['hours-per-week'].max())
df_people = data[data['hours-per-week'] == data['hours-per-week'].max()].shape[0]
df_salary = data[(data['salary'] == '>50K') & (data['hours-per-week'] == data['hours-per-week'].max())]
print("Количество людей, которые столько работают: ",df_people, "Процент зарабатывающих среди них больше 50К:", (df_salary.shape[0] / df_people) * 100)

Максимальное количество рабочих часов в неделю:  99
Количество людей, которые столько работают:  85 Процент зарабатывающих среди них больше 50К: 29.411764705882355


#### Задача №10. Посчитайте среднее количество рабочих часов в неделю (hours-per-week) для тех кто зарабатывает мало и много (salary) для каждой страны (native-country). ТЗ: =1 строка

In [47]:
data.groupby(['salary','native-country'])['hours-per-week'].mean()

salary  native-country            
<=50K   ?                             40.164760
        Cambodia                      41.416667
        Canada                        37.914634
        China                         37.381818
        Columbia                      38.684211
        Cuba                          37.985714
        Dominican-Republic            42.338235
        Ecuador                       38.041667
        El-Salvador                   36.030928
        England                       40.483333
        France                        41.058824
        Germany                       39.139785
        Greece                        41.809524
        Guatemala                     39.360656
        Haiti                         36.325000
        Holand-Netherlands            40.000000
        Honduras                      34.333333
        Hong                          39.142857
        Hungary                       31.300000
        India                         38.233333
     